FROM golang:1.12 as golang
COPY . /occollector
WORKDIR /occollector
RUN CGO_ENABLED=0 go build -o /occollector_linux ./cmd/occollector

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=golang occollector_linux /
ENTRYPOINT ["/occollector_linux"]
EXPOSE 55678
