FROM golang:1.12 as golang
COPY . /occollector
WORKDIR /occollector
RUN CGO_ENABLED=0 go build -mod=vendor -o /occollector_linux ./cmd/occollector

FROM debian:stretch-slim
RUN apt-get update && apt-get install ca-certificates curl openssl -y
COPY --from=golang occollector_linux /
ENTRYPOINT ["/occollector_linux"]
EXPOSE 55678
